### ISSUE TITLE
panic: runtime error: slice bounds out of range [3:1] in `GetURIPath`

### ISSUE THREAD

**Issue by Juneezee** [aws/aws-sdk-go-v2#1294]
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
I am using Minio for local development with S3. If I specific an endpoint `URL` without `http://`, it panics.

<details>
<summary>Output when I run the program</summary>

```shell
got this region: ap-southeast-1
panic: runtime error: slice bounds out of range [3:1]

goroutine 1 [running]:
github.com/aws/aws-sdk-go-v2/aws/signer/internal/v4.GetURIPath(0xc0000ee360, 0x0, 0x0)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/signer/internal/v4/util.go:54 +0x15e
github.com/aws/aws-sdk-go-v2/aws/signer/v4.(*httpSigner).Build(0xc00013c430, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000267a0, 0x0)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/signer/v4/v4.go:183 +0x675
github.com/aws/aws-sdk-go-v2/aws/signer/v4.Signer.SignHTTP(0x100, 0x857580, 0xc0000100c8, 0x0, 0x856e60, 0xc00007cb00, 0x85db60, 0xc000148480, 0x7e1c62, 0xa, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/signer/v4/v4.go:288 +0x2dd
github.com/aws/aws-sdk-go-v2/aws/signer/v4.(*SignHTTPRequestMiddleware).HandleFinalize(0xc0000a1e30, 0x85db60, 0xc000148480, 0x7d5780, 0xc0001483c0, 0x8583e0, 0xc000021530, 0x837fb96e80114a38, 0xc00013c900, 0xc00002b5c0, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/signer/v4/middleware.go:260 +0x6b5
github.com/aws/smithy-go/middleware.decoratedFinalizeHandler.HandleFinalize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_finalize.go:200
github.com/aws/aws-sdk-go-v2/aws/retry.MetricsHeader.HandleFinalize(0x85db60, 0xc000148480, 0x7d5780, 0xc0001483c0, 0x858340, 0xc00007cec0, 0xc000148201, 0x77a980, 0xa60988, 0x765720, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/retry/middleware.go:227 +0x46b
github.com/aws/smithy-go/middleware.decoratedFinalizeHandler.HandleFinalize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_finalize.go:200
github.com/aws/aws-sdk-go-v2/aws/retry.Attempt.handleAttempt(0x85db00, 0x85e4d8, 0xc0000d0580, 0x7fe6c8, 0x85db60, 0xc000148480, 0x7d5780, 0xc0001483c0, 0x858340, 0xc00007cee0, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/retry/middleware.go:136 +0x342
github.com/aws/aws-sdk-go-v2/aws/retry.Attempt.HandleFinalize(0x0, 0x85e4d8, 0xc0000d0580, 0x7fe6c8, 0x85db60, 0xc000148390, 0x7d5780, 0xc000148300, 0x858340, 0xc00007cee0, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/retry/middleware.go:86 +0x305
github.com/aws/smithy-go/middleware.decoratedFinalizeHandler.HandleFinalize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_finalize.go:200
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding.(*DisableGzip).HandleFinalize(0xa60988, 0x85db60, 0xc000148390, 0x7d5780, 0xc000148300, 0x858340, 0xc00007cf00, 0xc00007cf20, 0xc00013d120, 0xc00007cf20, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.1.0/accept_encoding_gzip.go:67 +0x167
github.com/aws/smithy-go/middleware.decoratedFinalizeHandler.HandleFinalize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_finalize.go:200
github.com/aws/smithy-go/middleware.(*FinalizeStep).HandleMiddleware(0xc0000100e8, 0x85db60, 0xc000148390, 0x7d5780, 0xc000148300, 0x858360, 0xc00007cc40, 0xc000021520, 0xfb3516a39570b22a, 0xa32800, ...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_finalize.go:114 +0x2a7
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.buildWrapHandler.HandleBuild(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_build.go:184
github.com/aws/aws-sdk-go-v2/aws/middleware.(*requestUserAgent).HandleBuild(0xc000021450, 0x85db60, 0xc000148390, 0x7d5780, 0xc000148300, 0x8582e0, 0xc0000214d0, 0xaa2a4d9647998a6, 0x10, 0x767760, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/middleware/user_agent.go:217 +0x233
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_build.go:200
github.com/aws/aws-sdk-go-v2/aws/signer/v4.(*contentSHA256Header).HandleBuild(0xa60988, 0x85db60, 0xc000148390, 0x7d5780, 0xc000148300, 0x858300, 0xc00007ce20, 0xa60988, 0x780080, 0xc000148360, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/signer/v4/middleware.go:205 +0x1e7
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_build.go:200
github.com/aws/aws-sdk-go-v2/aws/signer/v4.(*computePayloadSHA256).HandleBuild(0xa60988, 0x85db60, 0xc000148240, 0x7d5780, 0xc000148300, 0x858300, 0xc00007ce40, 0xc00002a118, 0xc00014a100, 0xc000028510, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/signer/v4/middleware.go:156 +0x279
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_build.go:200
github.com/aws/smithy-go/transport/http.(*ComputeContentLength).HandleBuild(0xa60988, 0x85db60, 0xc000148240, 0x7d5780, 0xc000148090, 0x858300, 0xc00007ce60, 0x149884ee879a2a4f, 0x0, 0xef9bdb8830c8954c, ...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/transport/http/middleware_content_length.go:55 +0x17c
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_build.go:200
github.com/aws/aws-sdk-go-v2/aws/middleware.ClientRequestID.HandleBuild(0x85db60, 0xc000148240, 0x7d5780, 0xc000148090, 0x858300, 0xc00007ce80, 0x50, 0x76f580, 0x7fc4852e5a78, 0x20, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/middleware/middleware.go:42 +0x1f0
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_build.go:200
github.com/aws/smithy-go/middleware.(*BuildStep).HandleMiddleware(0xc0000100e0, 0x85db60, 0xc000148240, 0x7d5780, 0xc000148090, 0x858360, 0xc00007cc60, 0xc00013da08, 0x0, 0x0, ...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_build.go:114 +0x2a7
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.serializeWrapHandler.HandleSerialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_serialize.go:192
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations.(*removeBucketFromPathMiddleware).HandleSerialize(0xa60988, 0x85db60, 0xc000148240, 0x758080, 0xa60988, 0x7d5780, 0xc000148090, 0x858420, 0xc0000214c0, 0xc000148210, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.10.0/internal/customizations/remove_bucket_middleware.go:27 +0x27a
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations.(*updateEndpoint).HandleSerialize(0xc00000e2b8, 0x85db60, 0xc000148240, 0x758080, 0xa60988, 0x7d5780, 0xc000148090, 0x8583a0, 0xc00007cd40, 0xc000148210, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.10.0/internal/customizations/update_endpoint.go:194 +0x21b
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/internal/s3shared.(*EnableDualstack).HandleSerialize(0xc00000e2a0, 0x85db60, 0xc000148240, 0x758080, 0xa60988, 0x7d5780, 0xc000148090, 0x8583a0, 0xc00007cd60, 0xc00002b598, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.4.0/update_endpoint.go:75 +0x1b9
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/s3.(*awsRestxml_serializeOpListBuckets).HandleSerialize(0xa60988, 0x85db60, 0xc000148240, 0x758080, 0xa60988, 0x7d5780, 0xc000148090, 0x8583a0, 0xc00007cd80, 0xc0000a1c20, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.10.0/serializers.go:4382 +0x433
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations.(*s3ObjectLambdaEndpoint).HandleSerialize(0xc00007cba0, 0x85db60, 0xc000148240, 0x758080, 0xa60988, 0x7d5780, 0xc000148090, 0x8583a0, 0xc00007cda0, 0xc000148210, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.10.0/internal/customizations/s3_object_lambda.go:37 +0x918
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations.(*processARNResource).HandleSerialize(0xc00007cb80, 0x85db60, 0xc000148240, 0x758080, 0xa60988, 0x7d5780, 0xc000148090, 0x8583a0, 0xc00007cdc0, 0xa60988, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.10.0/internal/customizations/process_arn_resource.go:54 +0x1c22
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/s3.(*ResolveEndpoint).HandleSerialize(0xc00000e288, 0x85db60, 0xc0001481e0, 0x758080, 0xa60988, 0x7d5780, 0xc000148090, 0x8583a0, 0xc00007cde0, 0x679d85, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.10.0/endpoints.go:112 +0x65a
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_serialize.go:208
github.com/aws/smithy-go/middleware.(*SerializeStep).HandleMiddleware(0xc000021400, 0x85db60, 0xc000148060, 0x758080, 0xa60988, 0x858360, 0xc00007cc80, 0x30, 0xc000148060, 0x7, ...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_serialize.go:122 +0x2dd
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.initializeWrapHandler.HandleInitialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_initialize.go:184
github.com/aws/smithy-go/middleware.(*setLogger).HandleInitialize(0xc000021440, 0x85db60, 0xc000148030, 0x758080, 0xa60988, 0x858400, 0xc000021470, 0xa60988, 0x780080, 0xc000148000, ...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/logging.go:45 +0xb5
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_initialize.go:200
github.com/aws/aws-sdk-go-v2/aws/middleware.RegisterServiceMetadata.HandleInitialize(0x7df6be, 0x2, 0x7df740, 0x2, 0xc00002e3c0, 0xe, 0x7e1fd6, 0xb, 0x85db60, 0xc0000a1d10, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.6.0/aws/middleware/metadata.go:40 +0xe7
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_initialize.go:200
github.com/aws/aws-sdk-go-v2/service/internal/s3shared.(*ARNLookup).HandleInitialize(0xc0000100f8, 0x85db60, 0xc0000a1d10, 0x758080, 0xa60988, 0x858380, 0xc00007cd00, 0xc00007cd20, 0xc00013f5c8, 0xc00007cd20, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.4.0/arn_lookup.go:39 +0xca
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_initialize.go:200
github.com/aws/smithy-go/middleware.(*InitializeStep).HandleMiddleware(0xc0000100d8, 0x85db60, 0xc0000a1d10, 0x758080, 0xa60988, 0x858360, 0xc00007cca0, 0xc00007ccc0, 0xc00013f6c0, 0xc00007ccc0, ...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/step_initialize.go:114 +0x2a7
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.(*Stack).HandleMiddleware(0xc000088b40, 0x85db60, 0xc0000a1d10, 0x758080, 0xa60988, 0x858440, 0xc000021460, 0xc00007cc20, 0xc00013f8e8, 0xc00007cc20, ...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/stack.go:109 +0x1ad
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
        /home/jun/go/pkg/mod/github.com/aws/smithy-go@v1.4.0/middleware/middleware.go:57
github.com/aws/aws-sdk-go-v2/service/s3.(*Client).invokeOperation(0xc0000b3e00, 0x85daf0, 0xc00002a110, 0x7e1fd6, 0xb, 0x758080, 0xa60988, 0x0, 0x0, 0x0, ...)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.10.0/api_client.go:165 +0x59d
github.com/aws/aws-sdk-go-v2/service/s3.(*Client).ListBuckets(0xc0000b3e00, 0x85daf0, 0xc00002a110, 0x0, 0x0, 0x0, 0x0, 0x7fe770, 0x0, 0xc000088b00)
        /home/jun/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.10.0/api_op_ListBuckets.go:21 +0xf7
main.run(0x401230, 0x0)
        /home/jun/Desktop/s3/main3.go:43 +0x326
main.main()
        /home/jun/Desktop/s3/main3.go:16 +0x25

```

</details>

**Version of AWS SDK for Go?**
v1.6.0

**Version of Go (`go version`)?**
```shell
$ go version
go version go1.16.5 linux/amd64
```

**To Reproduce (observed behavior)**
```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	resolver := aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
		return aws.Endpoint{
			URL: "localhost:9000", // panic
			// URL: "http://localhost:9000", // doesn't panic
		}, nil
	})

	creds := credentials.NewStaticCredentialsProvider("minioadmin", "minioadmin", "")
	cfg, err := config.LoadDefaultConfig(context.Background(),
		config.WithCredentialsProvider(creds),
		config.WithEndpointResolver(resolver),
	)
	if err != nil {
		return err
	}

	fmt.Printf("got this region: %v\n", cfg.Region)
	svc := s3.NewFromConfig(cfg)

	ctx := context.Background()

	buckets, err := svc.ListBuckets(ctx, nil) // panic occurs here
	if err != nil {
		return err
	}

	for _, bucket := range buckets.Buckets {
		fmt.Printf("I see bucket \"%s\"\n", *bucket.Name)
	}

	return nil
}
```

**Expected behavior**
`config.LoadDefaultConfig` should return an error if `URL` must be prefixed with a scheme. Otherwise, I expect the endpoint resolver to be able to use `URL` without a scheme.

**Additional context**
N/A

**Comment by zapling** [comment]
Thanks @Juneezee, indeed setting the protocol fixes this weird panic.

**Comment by alexrudd** [comment]
Just hit this panic too

**Comment by jasdel** [comment]
Thanks for the update @alexrudd. Do you have any details available how you were able to reproduce this issue? In addition could you include the version of the SDK that you are using?

**Comment by qburst-samir** [comment]
I experienced this after I incorrectly configured the `aws.Endpoint`'s URL field when populating the `aws.Config` at the beginning.

The `URL` field is generally expected to be a `http://host:port` format string, hence the `GetURIPath` looking for the 4th 'split-by-a-slash' element (`strings.Split(u.Opaque, "/")[3:]` u being a `url.URL` object), since the splits would generally be `["http:","","host:port",<URI>...]`

**Comment by chofnar** [comment]
I ran into this too with SDK v1.16.5. @jasdel the code provided by @Juneezee looks about right: `resolver := aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
		return aws.Endpoint{
			URL: "localhost:9000", // panic
			// URL: "http://localhost:9000", // doesn't panic
		}, nil
	})`

**Comment by jasdel** [comment]
Thanks for updating this issue. I've put out PR #1754 that corrects how the SDK's signer is handling opaque URL paths. The PR also added several tests that should prevent this kind of issue in the future.
