### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by Redw0od** [aws/aws-sdk-go-v2#1445]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
Attempted to import a route53 record into the terraform state. with the following command:
terragrunt import aws_route53_record.vault_lb 'Z00183233SDI3XXXXXXX_vault.euw1.prod.XXXXXXXX.net'

**Version of AWS SDK for Go?**
Terraform v1.0.7 on darwin_amd64
terraform-provider-aws_v3.60.0_x5

**To Reproduce (observed behavior)**
run the import command above.

**Expected behavior**
Successful resource import

**Additional context**
Stack trace from the terraform-provider-aws_v3.60.0_x5 plugin:

panic: runtime error: slice bounds out of range [:-1]

goroutine 88 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.parseRecordId(0xc0025ba700, 0x31, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_route53_record.go:976 +0x4d2
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsRoute53RecordRead(0xc0025bc680, 0x7320da0, 0xc00077e000, 0xc7c60f0, 0xc000180d80)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_route53_record.go:515 +0x1b57
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0010c0a80, 0x8d845e8, 0xc000321240, 0xc0025bc680, 0x7320da0, 0xc00077e000, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0010c0a80, 0x8d845e8, 0xc000321240, 0xc002394380, 0x7320da0, 0xc00077e000, 0xc000d1c2c0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000398f18, 0x8d845e8, 0xc000321240, 0xc000321280, 0xc000321240, 0x100b665, 0x7c8ede0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0026d1340, 0x8d84690, 0xc000321240, 0xc0026152c0, 0xc0026d1340, 0xc000467080, 0xc000130ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x7f7ec20, 0xc0026d1340, 0x8d84690, 0xc000467080, 0xc002615260, 0x0, 0x8d84690, 0xc000467080, 0xc0003c0580, 0x15b)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002bb180, 0x8da7098, 0xc00195b080, 0xc0025aa100, 0xc0019caea0, 0xc784a90, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002bb180, 0x8da7098, 0xc00195b080, 0xc0025aa100, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00072e8c0, 0xc0002bb180, 0x8da7098, 0xc00195b080, 0xc0025aa100)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.60.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

ERRO[0016] 1 error occurred:
        * exit status 1

**Comment by skmcgrail** [comment]
Please open an issue to the [terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws) project, issues cut to this GitHub repository should be specific to bug reporting or features requests for the AWS SDK for Go V2 SDK specifically.
