### ISSUE TITLE
Panic on nil dereference when using DynamoDB Local

### ISSUE THREAD

**Issue by sudhirj** [aws/aws-sdk-go-v2#258]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2, on master (ba9304b04871ecd1a51e24a237ae354b06d970ef)

### Version of Go (`go version`)?
go version go1.11.4 darwin/amd64

### What issue did you see?
```
Panic in github.com/aws/aws-sdk-go-v2/private/protocol/rest.UnmarshalMeta(0xc000114a00)
	/Users/sudhir/workspace/src/github.com/aws/aws-sdk-go-v2/private/protocol/rest/unmarshal.go:35 +0x35
```

### Steps to reproduce

Trying running the following code against a Dynamodb local server:
```
func setup() {
	name := "test1"
	cfg := aws.Config{
		EndpointResolver: aws.ResolveWithEndpointURL("http://localhost:8000"),
		Region:           "eu-west-2",
		Credentials: aws.StaticCredentialsProvider{Value: aws.Credentials{
			AccessKeyID:     "AK1",
			SecretAccessKey: "SK1",
		}},
	}
	dynamoService := dynamodb.New(cfg)
	resp, err := dynamoService.CreateTableRequest(&dynamodb.CreateTableInput{
		TableName: aws.String(name),
		AttributeDefinitions: []dynamodb.AttributeDefinition{
			{AttributeName: aws.String("partkey"), AttributeType: "S"},
			{AttributeName: aws.String("sortkey"), AttributeType: "S"},
			//{AttributeName: aws.String("data"), AttributeType: "S"},
		},
		KeySchema: []dynamodb.KeySchemaElement{
			{AttributeName: aws.String("partkey"), KeyType: dynamodb.KeyTypeHash},
			{AttributeName: aws.String("sortkey"), KeyType: dynamodb.KeyTypeRange},
		},
		GlobalSecondaryIndexes: []dynamodb.GlobalSecondaryIndex{{
			IndexName: aws.String("inversion"),
			KeySchema: []dynamodb.KeySchemaElement{
				{ AttributeName: aws.String("sortkey"), KeyType: dynamodb.KeyTypeHash},
				{ AttributeName: aws.String("partkey"), KeyType: dynamodb.KeyTypeRange},
			},
			Projection: &dynamodb.Projection{ProjectionType: dynamodb.ProjectionTypeKeysOnly},
		}},
	}).Send()
	log.Println(resp, err)	
}
```
I receive the following stacktrace:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1349255]

goroutine 21 [running]:
testing.tRunner.func1(0xc000124400)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:792 +0x387
panic(0x14f2d40, 0x19e53d0)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
github.com/aws/aws-sdk-go-v2/private/protocol/rest.UnmarshalMeta(0xc000114a00)
	/Users/sudhir/workspace/src/github.com/aws/aws-sdk-go-v2/private/protocol/rest/unmarshal.go:35 +0x35
github.com/aws/aws-sdk-go-v2/private/protocol/jsonrpc.UnmarshalMeta(0xc000114a00)
	/Users/sudhir/workspace/src/github.com/aws/aws-sdk-go-v2/private/protocol/jsonrpc/jsonrpc.go:73 +0x2b
github.com/aws/aws-sdk-go-v2/aws.(*HandlerList).Run(0xc000114cf8, 0xc000114a00)
	/Users/sudhir/workspace/src/github.com/aws/aws-sdk-go-v2/aws/handlers.go:195 +0x98
github.com/aws/aws-sdk-go-v2/aws.(*Request).Send(0xc000114a00, 0x0, 0x0)
	/Users/sudhir/workspace/src/github.com/aws/aws-sdk-go-v2/aws/request.go:508 +0x2f0
github.com/aws/aws-sdk-go-v2/service/dynamodb.CreateTableRequest.Send(0xc000114a00, 0xc0001a7d40, 0xc0000a1350, 0xc0001a7d40, 0xc0000a1350, 0xc0000e2320)
	/Users/sudhir/workspace/src/github.com/aws/aws-sdk-go-v2/service/dynamodb/api.go:458 +0x2f
```
If you have have an runnable example, please include it.

Included above. If I'm making a mistake somewhere, if would be great to get a more descriptive error message.

**Comment by sudhirj** [comment]
This was a configuration problem, I had to use the local config that I was running the dynamodb local server with. Worked after I switched to `cfg, err := external.LoadDefaultAWSConfig()` and customized it with

```
cfg.EndpointResolver = aws.ResolveWithEndpointURL("http://localhost:8000")
cfg.Region = "ap-south-1"
cfg.DisableEndpointHostPrefix = true
```
