### ISSUE TITLE
s3manager: Uploader panics when custom metadata is provided

### ISSUE THREAD

**Issue by fsouza** [aws/aws-sdk-go-v2#88]
### Version of AWS SDK for Go?

Current master as of 2018-01-10: 14d1593063ec4c5c47f94db30a57d10e8c044f9a

### Version of Go (`go version`)?

```
% go version
go version devel +9044f018ec Tue Jan 9 01:53:38 2018 +0000 darwin/amd64
```

### What issue did you see?

s3manager.Uploader panics when uploading an object with custom metadata.

### Steps to reproduce

Code (make sure to set the bucket name): https://play.golang.org/p/l1nWAdGf_qT

Output:

```
% go run upload.go
panic: reflect.Set: value of type map[string]*string is not assignable to type map[string]string

goroutine 1 [running]:
reflect.Value.assignTo(0x139e400, 0xc4206c4030, 0x15, 0x14342cc, 0xb, 0x139ebe0, 0x0, 0x139e400, 0xc4206c4030, 0x15)
	/Users/fsouza/.gimme/versions/go/src/reflect/value.go:2235 +0x41d
reflect.Value.Set(0x139ebe0, 0xc4206c6090, 0x195, 0x139e400, 0xc4206c4030, 0x15)
	/Users/fsouza/.gimme/versions/go/src/reflect/value.go:1373 +0xa4
github.com/aws/aws-sdk-go-v2/internal/awsutil.rcopy(0x139ebe0, 0xc4206c6090, 0x195, 0x139e400, 0xc42012c230, 0x195, 0xc4206c6000)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/internal/awsutil/copy.go:97 +0xc3f
github.com/aws/aws-sdk-go-v2/internal/awsutil.rcopy(0x142a820, 0xc4206c6000, 0x199, 0x14287a0, 0xc42012c1c0, 0x199, 0x1)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/internal/awsutil/copy.go:78 +0x261
github.com/aws/aws-sdk-go-v2/internal/awsutil.rcopy(0x14194a0, 0xc4206c6000, 0x16, 0x1373820, 0xc42012c1c0, 0x16, 0x101)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/internal/awsutil/copy.go:68 +0x8e7
github.com/aws/aws-sdk-go-v2/internal/awsutil.Copy(0x14194a0, 0xc4206c6000, 0x1373820, 0xc42012c1c0)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/internal/awsutil/copy.go:21 +0xb9
github.com/aws/aws-sdk-go-v2/service/s3/s3manager.(*uploader).singlePart(0xc420177ea0, 0x14a50c0, 0xc4206c4000, 0x1, 0x14a39e0, 0xc420010050)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/service/s3/s3manager/upload.go:558 +0x65
github.com/aws/aws-sdk-go-v2/service/s3/s3manager.(*uploader).upload(0xc420177ea0, 0x0, 0x0, 0x0)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/service/s3/s3manager/upload.go:458 +0x537
github.com/aws/aws-sdk-go-v2/service/s3/s3manager.Uploader.UploadWithContext(0x500000, 0x5, 0x0, 0x2710, 0x14aca40, 0xc420011260, 0x0, 0x0, 0x0, 0x1c08210, ...)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/service/s3/s3manager/upload.go:376 +0x184
github.com/aws/aws-sdk-go-v2/service/s3/s3manager.Uploader.Upload(0x500000, 0x5, 0x0, 0x2710, 0x14aca40, 0xc420011260, 0x0, 0x0, 0x0, 0xc42012c1c0, ...)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/service/s3/s3manager/upload.go:347 +0xc4
main.main()
	/Users/fsouza/upload.go:17 +0x41b
exit status 2
```

**Comment by jasdel** [comment]
Thanks for posting this @fsouza This is a bug that was missed when we migrated the SDK to not use pointers for collection types (maps and slices). This should be a pretty simple fix for the SDK by just updating the `s3manager.UploadInput`'s Metadata field types to be `map[string]string`.  There might be a few other fields that are similarly effected in that package.

If you're looking to create a PR we'd be glad to review it.

**Comment by fsouza** [comment]
@jasdel cool, thanks for the info! I'll prepare a PR :)

**Comment by fsouza** [comment]
@jasdel I just submitted #89. Thanks!
